### ISSUE TITLE
Maven Repository offline? 

### ISSUE THREAD

**Issue by faeldix** [FDVSolutions/DynamicJasper#14]
HTTP ERROR 500

Problem accessing /repository/public1/. Reason:

    INTERNAL_SERVER_ERROR

Caused by:

java.lang.NullPointerException
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3357)
	at java.util.Arrays.asList(Arrays.java:3343)
	at org.apache.maven.archiva.webdav.util.IndexWriter.writeHyperlinks(IndexWriter.java:116)
	at org.apache.maven.archiva.webdav.util.IndexWriter.write(IndexWriter.java:70)
	at org.apache.maven.archiva.webdav.ArchivaDavResource.spool(ArchivaDavResource.java:223)
	at org.apache.jackrabbit.webdav.server.AbstractWebdavServlet.spoolResource(AbstractWebdavServlet.java:422)

**Comment by msgilligan** [comment]
Why not just publish on [bintray](http://bintray.com/)?

**Comment by juanalvarezg** [comment]
New repo, more information here: http://dynamicjasper.com/download/
