### ISSUE TITLE
DynamicJasper does not run with JasperReports 6.2.2 

### ISSUE THREAD

**Issue by mlehradt** [FDVSolutions/DynamicJasper#29]
DynamicJasper does not run with JasperReports 6.2.2 due to a ClassNotFoundException. (It still runs with 6.2.0, though…)
Caused by: java.lang.NoClassDefFoundError: net/sf/jasperreports/engine/util/JRProperties
at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperReport(DynamicJasperHelper.java:524)
at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperReport(DynamicJasperHelper.java:502)
at ar.com.fdvs.dj.core.DynamicJasperHelper.generateJasperPrint(DynamicJasperHelper.java:244)

**Comment by juanalvarezg** [comment]
Just released version 5.0.9 which supports JasperReports up to 6.3.0
Thank you for reporting the issue!
